//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tool.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação é permanente. Você tem certeza de que deseja continuar?.
        /// </summary>
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A exclusão é permanente. Você tem certeza de que deseja continuar?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro já existe.
        /// </summary>
        public static string DuplicateException {
            get {
                return ResourceManager.GetString("DuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de confirmação enviado.
        /// </summary>
        public static string EmailConfirmationSent {
            get {
                return ResourceManager.GetString("EmailConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de recuperação de senha enviado.
        /// </summary>
        public static string EmailRecoverSent {
            get {
                return ResourceManager.GetString("EmailRecoverSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser igual ao {1}.
        /// </summary>
        public static string EqualField {
            get {
                return ResourceManager.GetString("EqualField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar excluir o registro.
        /// </summary>
        public static string ErrorOnDelete {
            get {
                return ResourceManager.GetString("ErrorOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar salvar o registro.
        /// </summary>
        public static string ErrorOnSave {
            get {
                return ResourceManager.GetString("ErrorOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo não encontrado.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo foi selecionado.
        /// </summary>
        public static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique se você preencheu todos os campos obrigatórios.
        /// </summary>
        public static string FillAllRequiredField {
            get {
                return ResourceManager.GetString("FillAllRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha pelo menos um campo.
        /// </summary>
        public static string FilterRequired {
            get {
                return ResourceManager.GetString("FilterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu sua senha?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {counter} arquivos selecionados.
        /// </summary>
        public static string FormFile {
            get {
                return ResourceManager.GetString("FormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CPF válido.
        /// </summary>
        public static string InavalidCPF {
            get {
                return ResourceManager.GetString("InavalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro interno do servidor.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data deve ser informada no formato dd/mm/aaaa.
        /// </summary>
        public static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um documento válido.
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um e-mail válido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma imagem usando uma URL válida.
        /// </summary>
        public static string InvalidImageURL {
            get {
                return ResourceManager.GetString("InvalidImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infome um telefone válido.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma URL válida.
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser menor ou igual ao campo {1}.
        /// </summary>
        public static string LessOrEqualThan {
            get {
                return ResourceManager.GetString("LessOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser menor que o campo {1}.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso.
        /// </summary>
        public static string LogAccess {
            get {
                return ResourceManager.GetString("LogAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso GET.
        /// </summary>
        public static string LogAccessGet {
            get {
                return ResourceManager.GetString("LogAccessGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso POST.
        /// </summary>
        public static string LogAccessPost {
            get {
                return ResourceManager.GetString("LogAccessPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar.
        /// </summary>
        public static string LogErrorOnSave {
            get {
                return ResourceManager.GetString("LogErrorOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário efetuou logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvo com sucesso.
        /// </summary>
        public static string LogSuccessOnSave {
            get {
                return ResourceManager.GetString("LogSuccessOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve possuir no máximo {1} caracteres.
        /// </summary>
        public static string MaximumSize {
            get {
                return ResourceManager.GetString("MaximumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade mínima requerida {0}.
        /// </summary>
        public static string MinimumAgeRequired {
            get {
                return ResourceManager.GetString("MinimumAgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha pelo menos um campo {0} ou {1}.
        /// </summary>
        public static string MinimumOneRequired {
            get {
                return ResourceManager.GetString("MinimumOneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve possuir no mínino {1} caracteres.
        /// </summary>
        public static string MinimumSize {
            get {
                return ResourceManager.GetString("MinimumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser maior ou igual ao campo {1}.
        /// </summary>
        public static string MoreOrEqual {
            get {
                return ResourceManager.GetString("MoreOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser maior que o campo {1}.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item selecionado.
        /// </summary>
        public static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontrado.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro foi encontrado.
        /// </summary>
        public static string NothingToList {
            get {
                return ResourceManager.GetString("NothingToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verificação de robô é obrigatória.
        /// </summary>
        public static string NotRobotRequired {
            get {
                return ResourceManager.GetString("NotRobotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não mostrar novamente.
        /// </summary>
        public static string NotShowAgain {
            get {
                return ResourceManager.GetString("NotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excede o tamanho máximo.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando {0} — {1} de {2}.
        /// </summary>
        public static string PaginationHeader {
            get {
                return ResourceManager.GetString("PaginationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um caracter espercial (@@#$%&amp;*).
        /// </summary>
        public static string PasswordCharacter {
            get {
                return ResourceManager.GetString("PasswordCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mínimo 8 e no máximo 12 caracteres.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao menos uma letra maiúscula e uma minúscula (a-Z).
        /// </summary>
        public static string PasswordLetter {
            get {
                return ResourceManager.GetString("PasswordLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número (0-9).
        /// </summary>
        public static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha não atende as nossas políticas.
        /// </summary>
        public static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso.
        /// </summary>
        public static string PasswordUpdatedSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao menos um produto deve ser adicionado.
        /// </summary>
        public static string ProductRequired {
            get {
                return ResourceManager.GetString("ProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes selecione uma {0}.
        /// </summary>
        public static string SelectBeforeFemale {
            get {
                return ResourceManager.GetString("SelectBeforeFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes selecione um {0}.
        /// </summary>
        public static string SelectBeforeMale {
            get {
                return ResourceManager.GetString("SelectBeforeMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma {0}.
        /// </summary>
        public static string SelectOneFemale {
            get {
                return ResourceManager.GetString("SelectOneFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um {0}.
        /// </summary>
        public static string SelectOneMale {
            get {
                return ResourceManager.GetString("SelectOneMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão Expirou.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar padrão.
        /// </summary>
        public static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar imagem padrão.
        /// </summary>
        public static string SetDefaultImage {
            get {
                return ResourceManager.GetString("SetDefaultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir como vazio.
        /// </summary>
        public static string SetEmpty {
            get {
                return ResourceManager.GetString("SetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir como iguais.
        /// </summary>
        public static string SetSame {
            get {
                return ResourceManager.GetString("SetSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algum erro inesperado ocorrou.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi excluido com sucesso.
        /// </summary>
        public static string SuccessOnDelete {
            get {
                return ResourceManager.GetString("SuccessOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi salvo com sucesso.
        /// </summary>
        public static string SuccessOnSave {
            get {
                return ResourceManager.GetString("SuccessOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token informado não é existe ou expirou.
        /// </summary>
        public static string TokenNotFoundOrExpired {
            get {
                return ResourceManager.GetString("TokenNotFoundOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não definido.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não conferem.
        /// </summary>
        public static string UnevenPassword {
            get {
                return ResourceManager.GetString("UnevenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário já em uso.
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
